### ISSUE TITLE
dependency to folder client\report\e2e

### ISSUE THREAD

**Issue by andreasmarkussen** [ankur841/Cucumber-UI#5]
When running with PhanthomJS. 
Then creation of the reports fails. 

The workaround is to create this folder manually.

 client\report\e2e

```
stderr: (node:4248) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

stdout: [14:45:33] E/launcher - Process exited with error code 1

stderr: Error: ENOENT: no such file or directory, mkdir 'C:\Tech\forks\cucumber-ui\client\build\report\e2e'
    at Object.fs.mkdirSync (fs.js:872:3)
    at Object.JsonFormatter.log (C:\Tech\forks\cucumber-ui\server\e2e\features\support\hook.js:34:8)
    at JSONFormatter.done (C:\Tech\forks\cucumber-ui\node_modules\gherkin\lib\gherkin\formatter\json_formatter.js:7:12)

```

**Comment by ankur-kushwaha** [comment]
Remove the support for phantomjs
